### PR TITLE
Add option --dump-sourceref to generate a file containing sourceKeys

### PR DESCRIPTION
**Pull request by bubeck**
This helps translators to find the context of a message to better understand the meaning of a message.
It generates (at the end of "extract") a file containing (mainly) sourceKeys in a meaningfull sorting order like:

````
[
  {
    "key": "Device init",
    "line": 384,
    "plural": false,
    "fileName": "../fc/fc.c"
  },
  {
    "key": "Device ready",
    "line": 388,
    "plural": false,
    "fileName": "../fc/fc.c"
  },
  ...
````

### CODE REVIEW

**Comment by puzrin** [comment]
I know about optional "context" in big systems. But is this really worth add for embedded? Usually simple text search in IDE shows all locations at once.

**Comment by puzrin** [comment]
Ok. If not urgent - let's keep it open for a while. I will think about possible solutions for this feature.

**Comment by bubeck** [comment]
Fine. I will rebase the PR to master, so that it does not use lodash anymore and is easily mergable. Stay tuned.

**Comment by puzrin** [comment]
https://github.com/lvgl/lv_i18n/commit/af62c7e2c95cbb332feb2121e41780cae05fb718 - polished some names.

After first refactoring pass, i found we can unify things even better - switch to concept of compiler/runtime lookup index.

Current "slow search" data:

```c
static lv_i18n_phrase_t en_gb_singulars[] = {
    {"s_en_only", "english only"},
    {"s_translated", "s translated"},
    {NULL, NULL} // End mark
};

#define _(text) lv_i18n_get_singular_by_map(text)
```

will become:

```c
// For slow search only
static const char * en_gb_singulars_idx[] = {
    "s_en_only",
    "s_translated"
    NULL // End mark
}

// The same as optimized
static const char * en_gb_singulars[] = {
  "english only", // 1=s_en_only
  "s translated", // 2=s_translated
  NULL, // 3="s_untranslated"
};

// The same thing, but with runtime index search
#define _(text) lv_i18n_get_singular_by_idx(text, get_singular_idx(text))
```

That will unify almost everything:

- Fast version will use macro index
- Slow version will contain extra index table + index search function.

And no more difference!

What to you think?

**Comment by bubeck** [comment]
Rebase done, merge with no problems, no objections or alternative solutions by puzrin. 
Is there any question open or please merge.

**Comment by bubeck** [comment]
Thanks for merging!

**Comment by kisvegabor** [comment]
Thanks for the activity here :slightly_smiling_face:

**Pull request merged**
