### PR TITLE
Add GitHub Action to execute tests and improve code quality

### PR DESCRIPTION
**Pull request by bubeck**
Add GitHub Actions to the project to ensure, everythings works.

### CODE REVIEW

**Comment by kisvegabor** [comment]
For some reason the Actions are not running: https://github.com/lvgl/lv_i18n/pull/69/checks

**Comment by kisvegabor** [comment]
Actions are enabled:
image

**Comment by bubeck** [comment]
It will only run the actions after you merged them into the master branch. Currently they come from my branch and will not be executed until PR is done. 

If you have merged, I can issue a new (trivial) PR so that you see, that they get executed. They will also be executed on every commit you do.

**Comment by bubeck** [comment]
If you merge this PR (and any other) I would recomment to use "squash", so that my commit history is combined into a single commit

**Comment by kisvegabor** [comment]
Okay, let's see. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Running but failing. :slightly_frowning_face:

**Comment by bubeck** [comment]
I see the problem. Good that we have the GitHub Actions, as there are smaller "lint" bugs. I will sent you PR this evening or tomorrow.

**Pull request merged**
